language: php

matrix:
  include:
    - php: 7.1
      env: LARAVEL=55
    - php: 7.1
      env: LARAVEL=56
    - php: 7.1
      env: LARAVEL=57
    - php: 7.1
      env: LARAVEL=58
    - php: 7.2
      env: LARAVEL=55
    - php: 7.2
      env: LARAVEL=56
    - php: 7.2
      env: LARAVEL=57
    - php: 7.2
      env: LARAVEL=58
    - php: 7.3
      env: LARAVEL=55
    - php: 7.3
      env: LARAVEL=56
    - php: 7.3
      env: LARAVEL=57
    - php: 7.3
      env: LARAVEL=58

services:
  - mysql

before_script:
  # Extensions: ext-uopz
  - if [ "$TRAVIS_PHP_VERSION" = "7.1" ] ; then pecl install uopz ; fi
  - if [ "$TRAVIS_PHP_VERSION" = "7.2" ] ; then pecl install uopz ; fi
#  - if [ "$TRAVIS_PHP_VERSION" = "7.3" ] ; then wget -O $TRAVIS_BUILD_DIR/uopz-5.0.2.tgz https://pecl.php.net/get/uopz-5.0.2.tgz ; fi
#  - if [ "$TRAVIS_PHP_VERSION" = "7.3" ] ; then tar xvf $TRAVIS_BUILD_DIR/uopz-5.0.2.tgz ; fi
#  - if [ "$TRAVIS_PHP_VERSION" = "7.3" ] ; then mv $TRAVIS_BUILD_DIR/uopz-5.0.2 $TRAVIS_BUILD_DIR/ext-uopz ; fi
#  - if [ "$TRAVIS_PHP_VERSION" = "7.3" ] ; then wget -O $TRAVIS_BUILD_DIR/ext-uopz/php73.patch https://gist.githubusercontent.com/cmb69/3060a552fc825497d066262ab31f3998/raw/428c0aee7d77b6c37ea3757bbc8b86cfc390d7ca/0001-Update-for-PHP-7.3.patch ; fi
#  - if [ "$TRAVIS_PHP_VERSION" = "7.3" ] ; then cd $TRAVIS_BUILD_DIR/ext-uopz && patch -p1 < php73.patch && phpize && ./configure && make && make install ; fi
  # Tests: Code Climate
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  # Packages: Install
  - composer self-update
  - composer install --prefer-source --no-interaction

script:
  # Packages: Laravel 5.5.x
  - if [ "$LARAVEL" = "55" ] ; then composer require "phpunit/phpunit:6.*" --no-update ; fi
  - if [ "$LARAVEL" = "55" ] ; then composer require "laravel/framework:5.5.*" --no-update ; fi
  - if [ "$LARAVEL" = "55" ] ; then composer require "orchestra/database:3.5.*" --no-update ; fi
  - if [ "$LARAVEL" = "55" ] ; then composer require "orchestra/testbench:3.5.*" --no-update ; fi
  # Packages: Laravel 5.6.x
  - if [ "$LARAVEL" = "56" ] ; then composer require "phpunit/phpunit:7.*" --no-update ; fi
  - if [ "$LARAVEL" = "56" ] ; then composer require "laravel/framework:5.6.*" --no-update ; fi
  - if [ "$LARAVEL" = "56" ] ; then composer require "orchestra/database:3.6.*" --no-update ; fi
  - if [ "$LARAVEL" = "56" ] ; then composer require "orchestra/testbench:3.6.*" --no-update ; fi
  # Packages: Laravel 5.7.x
  - if [ "$LARAVEL" = "57" ] ; then composer require "phpunit/phpunit:7.*" --no-update ; fi
  - if [ "$LARAVEL" = "57" ] ; then composer require "laravel/framework:5.7.*" --no-update ; fi
  - if [ "$LARAVEL" = "57" ] ; then composer require "orchestra/database:3.7.*" --no-update ; fi
  - if [ "$LARAVEL" = "57" ] ; then composer require "orchestra/testbench:3.7.*" --no-update ; fi
  # Packages: Laravel 5.8.x
  - if [ "$LARAVEL" = "58" ] ; then composer require "phpunit/phpunit:7.*" --no-update ; fi
  - if [ "$LARAVEL" = "58" ] ; then composer require "laravel/framework:5.8.*" --no-update ; fi
  - if [ "$LARAVEL" = "58" ] ; then composer require "orchestra/database:3.8.*" --no-update ; fi
  - if [ "$LARAVEL" = "58" ] ; then composer require "orchestra/testbench:3.8.*" --no-update ; fi
  # Packages: Update
  - composer update --prefer-source --no-interaction
  # Tests: Run
  - vendor/bin/phpunit --coverage-clover "$TRAVIS_BUILD_DIR/build/logs/clover.xml"

after_script:
  - ./cc-test-reporter after-build --coverage-input-type clover --prefix "$TRAVIS_BUILD_DIR" --exit-code $TRAVIS_TEST_RESULT

after_success:
  - vendor/bin/test-reporter
